name: 🚀 Deploy FinTrack via SSH

on:
  push:
    branches:
      - main  # Только при пуше в main

env:
  SERVER_USERNAME: root
  SERVER_IP: 168.119.255.188
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔽 Checkout repository
        uses: actions/checkout@v2

      - name: 🔐 SSH into server and pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            echo "📁 Переход в директорию проекта"
            cd /root/src/fintrack/FinTrack

            echo "💥 Жесткий сброс к origin/main"
            git fetch origin
            git reset --hard origin/main

          timeout: 120s
